#!/usr/bin/env python

import json, sys

try:
    import jwt
except:
    print("All work and no jwt module makes this script a dull script")
    sys.exit()

try:
    from pygments import highlight
    from pygments.lexers import JsonLexer
    from pygments.formatters import TerminalFormatter
    pygments_enabled = True
except:
    pygments_enabled = False
    


if len(sys.argv) > 1:
    encoded = sys.argv[1]
else:
    if not sys.stdin.isatty():
        encoded = sys.stdin.read().rstrip()
    else:
        print("""
Still missing the point, are you?

Try something like:
{} 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzb21lIjoicGF5bG9hZCJ9.Joh1R2dYzkRvDkqv3sygm5YyK8Gi4ShZqbhK2gxcs2U'
or
echo 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzb21lIjoicGF5bG9hZCJ9.Joh1R2dYzkRvDkqv3sygm5YyK8Gi4ShZqbhK2gxcs2U' | {}

            """.format(sys.argv[0],sys.argv[0]))
        sys.exit(1)

print("Type: {}, Length: {}".format(type(encoded), len(encoded)))

decoded = jwt.decode(encoded, verify=False)
indented = json.dumps(decoded, indent=4)


if pygments_enabled:
    print(highlight(indented, JsonLexer(), TerminalFormatter()))
else:
    print(indented)