#!/usr/bin/env python

import xmltodict
import json
import sys

if len(sys.argv) > 1:
    with open(sys.argv[1]) as fd:
        print(json.dumps(xmltodict.parse(fd.read())))
else:
    if not sys.stdin.isatty():
        print(json.dumps(xmltodict.parse(sys.stdin.read()), indent=4))
    else:
        print("Still missing the point, are you?")
