#!/usr/bin/env python
import yaml
import json
import sys

if len(sys.argv) > 1:
    with open(sys.argv[1]) as fd:
        print(json.dumps(yaml.load(fd.read()), indent=4))
else:
    if not sys.stdin.isatty():
        print(json.dumps(yaml.load(sys.stdin.read()), indent=4))
    else:
        print("Still missing the point, are you?")
